---
title: "Curriculum vitae"
description: ""
output:
  html_document:
    css: 
      - assets/cv/css/style.css
      - assets/cv/css/aos.css
      - assets/cv_custom.css
      - assets/cv/css/lightable.css
    template: assets/cv/template.html 
    includes:
      after_body: assets/cv_after_body.html
---

```{css, echo = FALSE}
.navbar {
  display: none; 
}
#navigation .navbar {
 display: block;
}
```
<!---
<div class="container">
<div id="navigation" class="menu-two">
<div class="navbar navbar-expand-lg">
<div class="navbar-header">
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"><i class="fa fa-align-justify"></i></span>
</button>
</div>
<div id="navbar-collapse" class="collapse navbar-collapse">
<nav id="mainmenu">
<ul class="nav navbar-nav">
<li class="scroll"><a href="#title">Home</a></li>
<li class="scroll"><a href="#experience">Experience</a></li>
<li class="scroll"><a href="#publications">Publications</a></li>
<li class="scroll"><a href="#software">Software</a></li>
<li class="scroll"><a href="#talks">Talks</a></li>
<li class="scroll"><a href="#workshops">Workshops</a></li>
<li class="scroll"><a href="#service">Service</a></li>
<li class="scroll"><a href="#talks">Talks</a></li>
<li class="scroll"><a href="#awards">Awards</a></li>
<li class="scroll"><a href="#contact">Contact</a></li>
</ul>
</nav>
</div>
</div>
</div>
</div>
--->

<div id="canvas">



```{r, child="../cv/cv.Rmd"}
```




</div>

<a href="cv.pdf">
<div class="download">
<i class="fas fa-file-pdf"></i> Click here for the PDF version.
</div>
</a>



```{r, include = FALSE}
fs::dir_copy("../cv/css/", "assets/cv/css", overwrite = TRUE)
fs::dir_copy("../cv/js/", "assets/cv/js", overwrite = TRUE)
fs::file_copy("../cv/template.html", "assets/cv/", overwrite = TRUE)
options(knitr.duplicate.label = "allow")
rmarkdown::render("../cv/cv.Rmd", 
                  output_file = "../cv/cv.html",
                  knit_root_dir = "../cv/")
pagedown::chrome_print("../cv/cv.html", 
                       output = "docs/cv.pdf")
```

