---
title: "Resources"
description: |
  This section contains some resources that are perhaps useful for others.
---

<style>
d-title {
 display:none;
}
d-article li, d-article ul {
  margin-bottom: 0em;
}
.small {
  font-size: 0.8rem;
}
</style>

# Resources

## Australia

### Professional societies 

* [Statistical Society of Australia](https://www.statsoc.org.au/)
   * ANZSTAT forum:
      * [General topics](https://www.statsoc.org.au/Forum-general-topics)
      * [Event announcment](https://www.statsoc.org.au/forum-event-announcements)
      * [Job vancancies and scholarships](https://www.statsoc.org.au/forum-job-vacancies)
   * [Events listing](https://www.statsoc.org.au/Events-listing)
* [International Biometrics Society Australasia Region](http://biometrics.org.au/)
* [Australian Mathematical Society](https://austms.org.au/)
<div class="small">
   * The society is (rightfully) mathematics oriented but occasionally features statistics. Contrary to common belief, statistics is *not* a subset of mathematics, although some areas of statistics have a large intersection with the field.
   * For women, [Women in Mathematics Special Interest Group](https://austms.org.au/special-interest-groups/wimsig/) (WIMSIG) may be of interest. I find [their newsletter](https://austms.org.au/special-interest-groups/wimsig/wimsig-news/) to be excellent. 
</div>

## Learning R 

* Australian Local [R-Ladies](https://rladies.org/) Chapters:
  * R-Ladies Melbourne [<i class="fab fa-meetup"></i>](https://www.meetup.com/en-AU/rladies-melbourne/) [<i class="fab fa-twitter"></i>](https://twitter.com/RLadiesMelb)
  * R-Ladies Sydney [<i class="fab fa-meetup"></i>](https://www.meetup.com/en-AU/rladies-sydney/) [<i class="fab fa-twitter"></i>](https://twitter.com/RLadiesSydney)
  * R-Ladies Canberra [<i class="fab fa-meetup"></i>](https://www.meetup.com/en-AU/rladies-canberra/) [<i class="fab fa-twitter"></i>](https://twitter.com/RLadiesCanberra)
  * R-Ladies Perth [<i class="fab fa-meetup"></i>](https://www.meetup.com/en-AU/rladies-perth/) [<i class="fab fa-twitter"></i>](https://twitter.com/RLadiesPerth)
  * R-Ladies Adelaide [<i class="fab fa-meetup"></i>](https://www.meetup.com/en-AU/rladies-adelaide/) [<i class="fab fa-twitter"></i>](https://twitter.com/RLadiesAdelaide)
  * R-Ladies Brisbane [<i class="fab fa-meetup"></i>](https://www.meetup.com/en-AU/rladies-brisbane/) [<i class="fab fa-twitter"></i>](https://twitter.com/RLadiesBrisbane)
* R for data science community [<i class="fas fa-globe"></i>](https://www.rfordatasci.com/) [<i class="fab fa-slack"></i>](https://rfordatascience.slack.com/join/shared_invite/zt-n46lijeb-2RRzQ70U34eH530~PyZsmg#/shared-invite/email)
* [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday)
* [Big Book of R](https://www.bigbookofr.com/)